### ISSUE TITLE
Add `lazytransform` to conda-forge

### ISSUE THREAD

**Issue by sugatoray** [AutoViML/lazytransform#1]
The following PR was merged. Now `lazytransform` is available on conda-forge.

- https://github.com/conda-forge/staged-recipes/pull/18621

Install it with:

```sh
conda install -c conda-forge lazytransform
```

**Comment by sugatoray** [comment]
Check package availability on conda-forge.

```sh
$ conda search -c conda-forge lazytransform
Loading channels: done
# Name                       Version           Build  Channel             
lazytransform                   0.41    pyhd8ed1ab_0  conda-forge
```

- https://anaconda.org/conda-forge/lazytransform

[![image](https://user-images.githubusercontent.com/10201242/162644035-2a8eb529-d8b7-495a-ae0e-80edae5001be.png)](https://anaconda.org/conda-forge/lazytransform)

**Comment by sugatoray** [comment]
cc: @AutoViML 

If it's okay with you, I would like to add you as a co-maintainer of the conda-forge feedstock.

- https://github.com/conda-forge/lazytransform-feedstock

PR to add `AutoViML` as new co-maintainer:

- https://github.com/conda-forge/lazytransform-feedstock/pull/1

**Comment by AutoViML** [comment]
Thank you @sugatoray 👍 for your great help in making lazytransform available through conda install.
Ram

**Comment by sugatoray** [comment]
@AutoViML It was my pleasure getting to help you out. 

Sugato. :)
