### ISSUE TITLE
Unpin requirements?

### ISSUE THREAD

**Issue by ecederstrand** [AutoViML/lazytransform#4]
lazytransform currently has restrictions on e.g. pandas<2.0 and scipy<1.11.0. These packages are getting a bit outdated. Is there anything holding back versions for these packages?

**Comment by AutoViML** [comment]
thank you for trying out lazytransform. LazyTransform is a pretty small library that relies on just a few other standard python libraries. It will be easy for you to upgrade to pandas-2.0 or whatever else that strikes your fancy and try and work with lazytransform.

But in my opinion, pandas 2.0 is a horrible release. They broke 1000's of libraries that have been working forever. Do you really want to upgrade to pandas 2.0 just for the sake of keeping up with your neighbors? I can fix lazytransform to handle pandas 2.0 but once your machine is upgraded to pandas-2.0, 1000's of other libraries will stop working. Are you ready to take that risk??

Scipy 1.11.1 was released in June 28, 2023 - that's less than a year old. How is that outdated??

Can you please answer the questions above and I will then act upon your recommendation...
Thanks
Ram

**Comment by ecederstrand** [comment]
Hi Ram,

See my comment in https://github.com/AutoViML/featurewiz/issues/112#issuecomment-2120340238 for a motivation.

Thanks!

**Comment by ecederstrand** [comment]
No longer using this package. Closing.
